### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by Visionishere** [baum1810/flowi#3]
Links: 0
Traceback (most recent call last):
  File "C:\Users\Vision\Downloads\flowi.py", line 98, in <module>
    main()
  File "C:\Users\Vision\Downloads\flowi.py", line 29, in main
    driver.execute_script('document.getElementById("generate").click()')
  File "C:\Users\Vision\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 500, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vision\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Vision\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read properties of null (reading 'click')
  (Session info: chrome=110.0.5481.78)
Stacktrace:
Backtrace:
        (No symbol) [0x002537D3]
        (No symbol) [0x001E8B81]
        (No symbol) [0x000EB36D]
        (No symbol) [0x000EE0FB]
        (No symbol) [0x000EDFD0]
        (No symbol) [0x000EEA35]
        (No symbol) [0x0015209F]
        (No symbol) [0x0013B41C]
        (No symbol) [0x00151215]
        (No symbol) [0x0013B216]
        (No symbol) [0x00110D97]
        (No symbol) [0x0011253D]
        GetHandleVerifier [0x004CABF2+2510930]
        GetHandleVerifier [0x004F8EC1+2700065]
        GetHandleVerifier [0x004FC86C+2714828]
        GetHandleVerifier [0x00303480+645344]
        (No symbol) [0x001F0FD2]
        (No symbol) [0x001F6C68]
        (No symbol) [0x001F6D4B]
        (No symbol) [0x00200D6B]
        BaseThreadInitThunk [0x76356BD9+25]
        RtlGetFullPathName_UEx [0x77478FD2+1218]
        RtlGetFullPathName_UEx [0x77478F9D+1165]
        (No symbol) [0x00000000]

Exception ignored in: <function Chrome.__del__ at 0x000001BCBE4949A0>
Traceback (most recent call last):
  File "C:\Users\Vision\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 788, in __del__
  File "C:\Users\Vision\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 743, in quit
OSError: [WinError 6] The handle is invalid

**Comment by Visionishere** [comment]
Fixed when I put in the cookie again, im not sure if it is changing or what
